### PR TITLE
Update prop type for EzRadioGroup 

### PR DESCRIPTION
**Pull request by onocy**
## What did we change?
- Update prop type for EzRadioGroup

## Why are we doing this?
- We are seeing errors in store-next related to this particular component not accepting an array of children as props, which is determined by this particular type

Unfortunately I found another issue when using the new minor release, so I'm just trying to include this one here for the future.

## Screenshot(s) / Gif(s):

Screen Shot 2023-02-15 at 3 28 43 PM

## Checklist

- [ ] Provide test coverage for the changes made
- [X] Create a changeset (`yarn changeset`) with a summary of the changes

[Contributing guidelines](https://ezcater.github.io/recipe/guides/contributing/)

### CODE REVIEW

**Review by pgrippi — DISMISSED** [review]

**Comment by onocy** [comment]
I'm converting back to draft since I think there are a couple of other places I can update here that I missed, sorry for the notifications 😞

**Comment by maggiedbaker** [comment]
> I'm converting back to draft since I think there are a couple of other places I can update here that I missed, sorry for the notifications 😞

Thanks for looking into this! I'm interested in this fix also, and am planning to wait for this to be released to [upgrade ezManage to 16.2](https://github.com/ezcater/ezcater-ezmanage-ui/pull/3909). @onocy Do you need any help?

**Comment by onocy** [comment]
I previously thought that there would need to be more components update in a similar way since I saw multiple failures when I ran the typescript compiler. It turns out they all necessitated the same change - this one! 
So I unnecessarily created an additional ticket really, I think this should solve most of our problems.

**Review by pgrippi — APPROVED** [review]

**Review by noranda — APPROVED** [review]

**Comment by noranda** [comment]
@maggiedbaker @onocy This PR has been released in [Recipe 16.3](https://ezcater.github.io/recipe/changelog)!

**Pull request merged**
