### PR TITLE
[DF-66] Page change handlers for EzCarousel

### PR DESCRIPTION
**Pull request by danidewitt**
## What did we change?
- Added `onPagePrevious` and `onPageNext` handler props to `EzCarousel`

## Why are we doing this?
- Allow actions to fire when user interacts with `EzCarousel`, closes https://github.com/ezcater/recipe/issues/683

## Screenshot(s) / Gif(s):
Screen Shot 2021-08-05 at 4 32 12 PM

Screen Shot 2021-08-05 at 4 32 53 PM

## Checklist

- [ ] Provide test coverage for the changes made
- [x] Create a changeset (`npm run changeset`) with a summary of the changes

[Contributing guidelines](https://ezcater.github.io/recipe/guides/contributing/)

### CODE REVIEW

**Review by morgannegagne — APPROVED** [review]
This is great! Thank you! 🎉

**Comment by danidewitt** [comment]
It's complaining about `New snapshot was not written. The update flag must be explicitly passed to write a new snapshot.` - @CraigCav do we need a new snapshot?

**Review by CraigCav — COMMENTED** [review]
Thanks for tackling this issue.

I think with a couple of changes we'll be able to land this for the store team. 

One challenge of triggering `onChange` callbacks within `useEffect` (or as the result of a `useEffect` call), is that we can end up with "changes" firing without user interaction, like during component initialization. Instead, we should try to always call `onChange` callbacks as a direct result of user interaction - typically within an event handler like `onClick` or `onScroll`.

We might also want to consider simplifying the API down to just `onPageChange` rather than necessarily `onPagePrevious` and `onPageNext` - the use case only calls to identify changes to the page, so by splitting this into two, we're forcing the user to wire up two event handlers instead of only needing one. Ultimately the "previous/next" data point can be inferred from the delta with the previous value, so is easily obtainable if downstream apps needed it.

**Comment by CraigCav** [comment]
We can probably leverage the `measure` callback inside `useCurrentPage`, since that is already wired up to only fire as a result of user interaction.

That makes this a pretty small  (`+6-5`) change to the codebase overall:

image

**Review by CraigCav — APPROVED** [review]

**Pull request merged**
