### PR TITLE
change minimum for EzProgress circle chart to 5% to always show a sliver of a color and change EzProgress circle chart size to 112 to match metricOnly square chart

### PR DESCRIPTION
**Pull request by danidewitt**
## What did we change?
- Changed EzProgress circle chart size from 110 to 112 to match the square chart
- Changed the minimum EzProgress circle chart value to 5% so that there's always a sliver of the chart visible, not just the grey background circle
- Added a test for the minimum value logic changes

## Why are we doing this?
See above.

## Screenshot(s) / Gif(s):
Screen Shot 2022-04-05 at 4 53 54 PM

A good test in the playroom:
```
<EzPage>
  <EzCard isQuiet>
    <EzLayout layout="basic">
      <EzProgress
        label="Q1 rejected orders goal - 3% of 0% goal"
        value={3}
        goal={0}
        metricOnly
        inverted
      />
      <EzProgress
        value={0}
        goal={90}
        subgoal={49}
        label="Q1 on-time delivery goal progress - 91%"
      />
    </EzLayout>
  </EzCard>
</EzPage>
```

## Checklist

- [x] Provide test coverage for the changes made
- [x] Create a changeset (`npm run changeset`) with a summary of the changes

[Contributing guidelines](https://ezcater.github.io/recipe/guides/contributing/)

### CODE REVIEW

**Comment by danidewitt** [comment]
visual regression tests
Screen Shot 2022-04-05 at 5 02 19 PM

**Comment by danidewitt** [comment]
visual regression tests
Screen Shot 2022-04-05 at 5 26 42 PM

**Comment by danidewitt** [comment]
visual regression tests
Screen Shot 2022-04-05 at 6 07 40 PM

**Review by pgrippi — APPROVED** [review]

**Comment by noranda** [comment]
Everything looks good, but I do have one question. Was the 5% chosen for a specific reason, or was it arbitrary? To me, 5% feels a bit too large when the value is 0%, potentially leading a user to wonder if the chart is accurate. Would a minimum of 2% be better here?

5%:
Screen Shot 2022-04-06 at 9 30 15 AM

2%:
Screen Shot 2022-04-06 at 9 26 14 AM

**Review by pgrippi — DISMISSED** [review]

**Review by noranda — APPROVED** [review]
Looks good!

**Pull request merged**
